"""empty message

Revision ID: 32764f7f9e2f
Revises: 
Create Date: 2020-02-03 11:04:50.428966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32764f7f9e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodicals', sa.Column('periodical_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodicals', 'periodical_date')
    # ### end Alembic commands ###
