"""empty message

Revision ID: e1e983403ad1
Revises: 32764f7f9e2f
Create Date: 2020-02-03 13:33:23.021012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1e983403ad1'
down_revision = '32764f7f9e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodicals', sa.Column('periodical_day', sa.String(length=5), nullable=True))
    op.add_column('periodicals', sa.Column('periodical_month', sa.String(length=5), nullable=True))
    op.add_column('periodicals', sa.Column('periodical_year', sa.String(length=5), nullable=True))
    op.drop_column('periodicals', 'periodical_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodicals', sa.Column('periodical_date', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('periodicals', 'periodical_year')
    op.drop_column('periodicals', 'periodical_month')
    op.drop_column('periodicals', 'periodical_day')
    # ### end Alembic commands ###
